# Generated by Django 5.2.1 on 2025-05-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """INSERT INTO store_collection (title) VALUES('collection1')""",
            """ DELETE FROM store_collection WHERE title='collection1' """
        )
    ]
