# Generated by Django 5.2.1 on 2025-05-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20250529_1309'),
        ('store', '0005_remove_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
    ]
